apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 195580718602.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googleclothes:eb4a43c07a5118733b57e4126c495a960867a83b
        ports:
        - containerPort: 80
