apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 195580718602.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googleclothes:ee96e86ac3cbd77ac398950f41f6c51b4b8af14a
        ports:
        - containerPort: 80
