apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 195580718602.dkr.ecr.us-east-1.amazonaws.com/shopping-site-electronics:811190be148e747fe52600355f41d51b0c643402
        ports:
        - containerPort: 80
