apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 195580718602.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlemusic:5c5e7d798fe297ef38f3341fe17d63b6f0ce203a
        ports:
        - containerPort: 80
