apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 195580718602.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlemusic:eb4a43c07a5118733b57e4126c495a960867a83b
        ports:
        - containerPort: 80
